package ndb.types;

/**
 * Created with IntelliJ IDEA.
 * User: ian
 * Date: 09/04/13
 * Time: 10:44 AM
 * To change this template use File | Settings | File Templates.
 */
public class GoogleNote
{
  public static final String  TABLE =    "googlenote_sync",

                              ID=                    "_id",            //perhaps works if multiple clients? probably not....
                              GOOGLE_ID =            "GOOGLE_ID",      //primary key, generated by google drive
                              GOOGLE_NBID=           "GOOGLE_NBID",
                              GOOGLE_DATE_MODIFIED=  "GOOGLE_DATE_MODIFIED",

                              //todo how does this work when multiple
                              LOCAL_ID=              "LOCAL_ID",
                              LOCAL_NBID=            "LOCAL_NBID",     //CAN GET FROM local_id...
                              LOCAL_DATE_MODIFIED=   "LOCAL_DATE_MODIFIED";



}   ///////////END CLASS/////////
