package ndb.types;

/**
 * Created with IntelliJ IDEA.
 * User: ian
 * Date: 09/04/13
 * Time: 10:53 AM
 * To change this template use File | Settings | File Templates.
 */
public class GoogleNotebook
{
  public static final String  TABLE =    "googlenotebook_sync",

//                              ID=                    "_id",            //perhaps works if multiple clients? probably not....
                              GOOGLE_ID =            "GOOGLE_ID",      //primary key, generated by google drive
 //                             GOOGLE_DATE_MODIFIED=  "GOOGLE_DATE_MODIFIED",


                              LOCAL_ID=              "LOCAL_ID",
//                              LOCAL_DATE_MODIFIED=   "LOCAL_DATE_MODIFIED";
                              TO_DELETE=            "TO_DELETE";

  /////////////////////////////////////////////////////////////////////////////////////////////////

  private int localGuid;
  private String serverGuid;
  private boolean toDelete; //determines whether entry should be deleted on next sync


  public GoogleNotebook(int localGuid)
  {
    setLocalGuid(localGuid);
    setToDelete(false);

    return;
  }


  public int getLocalGuid()
  {
    return localGuid;
  }

  public void setLocalGuid(int localGuid)
  {
    this.localGuid = localGuid;
  }

  public String getServerGuid()
  {
    return serverGuid;
  }

  public void setServerGuid(String serverGuid)
  {
    this.serverGuid = serverGuid;
  }


  public boolean isToDelete()
  {
    return toDelete;
  }

  public void setToDelete(boolean toDelete)
  {
    this.toDelete = toDelete;
  }
}   ///////////END CLASS/////////

